server:
  port: 8761

spring:
  application:
    name: spring-cloud-eureka-server

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    preferIpAddress: true      #指定通过IP注册,一般服务集群时配置,需要ip-address参数一起设置(保证hostName和ip-address一样)，以免eureka管理页面出现不可用分片提示信息(unavailable-replicas),服务的注册默认是通过hostName注册的，当判断注册的hostName和服务
    ip-address: ${EUREKA_IP:${eureka.instance.hostname}} #强制指定eureka的ip地址
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
  server:
    #开启自我保护
    enable-self-preservation: false
    #启用主动失效，并且每次主动失效检测间隔为3s
    #默认60s
    eviction-interval-timer-in-ms: 3000
    #eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
    #由于启用了evict其实就用不太上改这个配置了
    #默认180s
    responseCacheAutoExpirationInSeconds: 180
    #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    #默认30s
    responseCacheUpdateInvervalMs: 3000
  client:
    #eureka client刷新本地缓存时间
    #默认30s
    registryFetchIntervalSeconds: 5
    #将自己注册到服务中心，集群时需要设置为true
    registerWithEureka: true
    #服务中心互相同步，集群时需要设置为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:8762/eureka/,http://localhost:8761/eureka/
  ribbon:
    #eureka客户端ribbon刷新时间
    #默认30s
    ServerListRefreshInterval: 1000


logging:
  level:
    com.netflix: warn
