spring:
  application:
    name: service-system

eureka:
  instance:
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
    preferIpAddress: true
  client:
    #eureka client刷新本地缓存时间
    #默认30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://${spring.cloud.client.ip-address}:8762/eureka/

info:
  app:
    name: "服务调用"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'  #SpringBootActuator监控暴露所有接口

